### ISSUE TITLE
Docs are wrong about cargo package name.

### ISSUE THREAD

**Issue by kitsuneninetails** [pipefy/datadog-apm-rust#2]
Should be added to cargo.toml as:

```
datadog-apm = "0.1"
```

not 

```
datadog_apm = "0.1"
```

as stated.

**Comment by fhsgoncalves** [comment]
Nice catch! Thank you!

It was fixed on: https://github.com/pipefy/datadog-apm-rust/commit/f846981369020130ae63d2679780eafdd37ec07d
